javascript_compressor: closure
template_function:     dc._.template
embed_assets:          datauri
gzip_assets:           off

javascripts:
  search_embed:
    - public/javascripts/vendor/underscore/underscore.js
    - public/javascripts/vendor/jquery/dist/jquery.js
    - public/javascripts/vendor/backbone/backbone.js
    - public/javascripts/lib/inflector.js
    - public/javascripts/embed/search_embed.js
    - app/views/jst/embed/search_*.jst

stylesheets:
  search_embed:
    - public/stylesheets/embed/search_embed.css
