# This is a standard ActiveRecord database.yml file. You can configure it
# to use any database that ActiveRecord supports.

<% secrets = YAML.load_file('secrets/secrets.yml')['development'] %>

:adapter:  postgresql
:encoding: unicode
:schema_search_path: public
:pool: 10
:dead_connection_timeout: 1
:reaping_frequency: 30
:username: <%= secrets['username'] %>
:password: <%= secrets['db_password'] %>
:allow_concurrency: true
:database: dcloud_crowd_development
:host:     dev.dcloud.org
